os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang
  
env:
  - CODYCO_ICUBWBI_USE_EXTERNAL_TORQUE=True, CODYCO_YARP_FROM_SUPERBUILD=True
  - CODYCO_ICUBWBI_USE_EXTERNAL_TORQUE=False, CODYCO_YARP_FROM_SUPERBUILD=False
  
matrix:
  allow_failures:
  - os: osx 
  - env: CODYCO_YARP_FROM_SUPERBUILD=True
  
before_script:
  - sh .ci/travis-deps.sh
  
script:
  - sh .ci/travis-build.sh

notifications:
  email:
    - pegua1@gmail.com
