os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang
  
env:
  - CODYCO_ICUBWBI_USE_EXTERNAL_TORQUE=True
  - CODYCO_ICUBWBI_USE_EXTERNAL_TORQUE=False
  
matrix:
  allow_failures:
  - os: osx 
  
before_script:
  - sh .ci/travis-deps.sh
  
script:
  - sh .ci/travis-build.sh

notifications:
  email:
    - pegua1@gmail.com
