version: 1.0.{build}
os: unstable

branches:
  except:
  - travis

clone_folder: c:\my dev\codyco-superbuild

environment:
  ACE_ROOT:          c:/Program Files (x86)/robotology/ace-6.1.1
  GSL_DIR:           c:/Program Files (x86)/robotology/gsl-1.14
  IPOPT_DIR:         c:/Program Files (x86)/robotology/ipopt-3.10.1
  OpenCV_DIR:        c:/Program Files (x86)/robotology/opencv-2.4.9
  Qt5_DIR:           c:/Program Files (x86)/robotology/Qt-5.4.1_v12_x86
  YARP_DIR:          c:/Program Files (x86)/robotology/yarp-2.3.64
  ICUB_DIR:          c:/Program Files (x86)/robotology/icub-1.1.16
  BOOST_ROOT:        C:\Libraries\boost
  BOOST_LIBRARYDIR:  C:\Libraries\boost\lib32-msvc-12.0
  

install:
  - ps: >-
      $dwntool = New-Object System.Net.WebClient
      
      $Stoploop = $false
      
      do {
          try {
            $dwntool.DownloadFile('https://github.com/robotology/yarp/releases/download/v2.3.64/yarp_2.3.64_v12_x86_1.exe','c:\dev\yarp.exe')
            $dwntool.DownloadFile('https://github.com/robotology/icub-main/releases/download/v1.1.16/iCub_1.1.16_v12_x86_2.exe','c:\dev\icub.exe')
            $dwntool.DownloadFile('https://raw.githubusercontent.com/robotology/icub-main/master/conf/iCubHelpers.cmake','c:\dev\iCubHelpers.cmake')
            $Stoploop = $true
          }
          catch {
            Start-Sleep -Seconds 15
          }
      }
      While ($Stoploop -eq $false)
      
      
  - cmd: start "" /WAIT "c:\dev\yarp.exe" /S
  - cmd: timeout 10
  - cmd: start "" /WAIT "c:\dev\icub.exe" /S
  - cmd: timeout 10
  - cmd: dir "c:\Program Files (x86)\robotology"


build:

build_script:
  - cd c:\my dev\codyco-superbuild
  - md build
  - cd build
  - cmake -G"Visual Studio 12" -DNON_INTERACTIVE_BUILD:BOOL=TRUE -DYCM_BOOTSTRAP_VERBOSE:BOOL=TRUE ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" codyco-superbuild.sln

notifications:
  email:
  - silvio.traversaro@iit.it
  
